### ISSUE TITLE
[registration] Raed Zorkot

### ISSUE THREAD

**Issue by RaedZorkot** [teamshadi/ssoc18#10]
## If you are registering for SSOC18 ...

Please fill in the below form:

1. Name: Raed Zorkot.
2. University: American University of Beirut.
3. Department: Computer and Communication Engineering.
4. Expected graduation date: May 2019.
5. How's your availability during July?  All day.
6. How's your availability during August? All day.
7. Which project are you interested in? (please choose on of the options below)
  a. (financial engineering) Market-making cryptocurrencies
  b. (chemical engineering) AI on cosmetics
 
8. Most information on this event as well as code is made public by being posted on github.com. Are you ok with that? Yes.
9. Special notes? 

## If you are just making a general inquiry ...

Go ahead

**Comment by shadiakiki1986** [comment]
Thanks for registering. I will open a new issue with your first task
