### ISSUE TITLE
[MickMek] btcusd monitor sends multiple alerts per day about the same price change (~2h)

### ISSUE THREAD

**Issue by shadiakiki1986** [teamshadi/ssoc18#13]
@MickMek I got 6 emails from `market.eye.alerts@gmail.com` this morning saying `ALERT! PRICE HIKE >5%`. Let's
- post an image here of the plot of best bid/ask since the start of the recording
- check why the script was unable to identify that it had already sent an alert
- show the list of recipients in the email
  - ATM I only see an empty list of recipients
  - maybe you're using `BCC` ?

**Comment by MickMek** [comment]
Below are the plots of spread+standard deviation, spread, and minimum_ask+maximum_bid respectively:

![unknown](https://user-images.githubusercontent.com/40487507/42814178-168ab05a-89cc-11e8-9c92-0fbf8ab6f7d0.jpg)
![unknown-2](https://user-images.githubusercontent.com/40487507/42814181-1a5cf63e-89cc-11e8-84ae-10f8804793e1.jpg)
![unknown-3](https://user-images.githubusercontent.com/40487507/42814187-1cc511a4-89cc-11e8-9939-48d6cb99408f.jpg)

**Comment by MickMek** [comment]
The curl added to the cron job was supposed to avoid multiple messages being sent for the same event. 
currently, the crontab is set as:
`2 * * * * python3 ./1-btc_order_book_monitor/scripts/2.2-mick-market_eye.py             && curl -fsS--retry 3 https://hc-ping.com/3bc3aa60-0a7d-442c-8d47-793b478527ae > /dev/null`

Do you think changing it to the below would give better results?
`2 * * * * python3 ./1-btc_order_book_monitor/scripts/2.2-mick-market_eye.py             && curl -f -s -S --retry 3 https://hc-ping.com/3bc3aa60-0a7d-442c-8d47-793b478527ae > /dev/null`

**Comment by shadiakiki1986** [comment]
The curl added to the cron job has nothing to do with duplicated
notifications. It's just a heartbeat sent to healthchecks.io to monitor
that it's running. You'll have to add your own logic in the 2.2-...py file
to avoid multiple alerts about the same event

**Comment by MickMek** [comment]
Alright sorry for the confusion, the `2.2-mick-market_eye.py` script has been modified to notify only once a day. Once the price surpasses the threshold of 5%, it will notify the mailing list and will not notify for the rest of the day, even if the price rises again for another 5%.

Recipients are now visible in the email.

**Comment by shadiakiki1986** [comment]
I just git an alert from healthchecks.io that this script is down (has erro)

**Comment by MickMek** [comment]
Please inform me if the error persists in the coming hour

**Comment by shadiakiki1986** [comment]
LGTM
