### ISSUE TITLE
[registration] Karim Al Chammas

### ISSUE THREAD

**Issue by karimchammas** [teamshadi/ssoc18#16]
## If you are registering for SSOC18 ...

Please fill in the below form:

1. Name: Karim Al Chammas
2. University: American University of Beirut
3. Department: Civil and Environmental Engineering
4. Expected graduation date: June 2018
5. How's your availability during July? a couple of hours per day 
6. How's your availability during August? a couple of hours per day
7. Which project are you interested in? (please choose on of the options below)
  a. (financial engineering) Market-making cryptocurrencies
8. Most information on this event as well as code is made public by being posted on github.com. Are you ok with that? Yes
9. Special notes? ...

## If you are just making a general inquiry ...

Go ahead

**Comment by shadiakiki1986** [comment]
Ok thanks for registering.
