### ISSUE TITLE
[MohammadAliHamdan] scrapy tutorial (~5h)

### ISSUE THREAD

**Issue by shadiakiki1986** [teamshadi/ssoc18#18]
@MohammadAliHamdan

Please follow the scrapy tutorial [here](https://doc.scrapy.org/en/latest/intro/tutorial.html) and when done let's talk so you show me what you've done

**Comment by ma-hamdan** [comment]
I finished the tutorial, didn't find real problems. I am ready to use Scrapy for the next task,

**Comment by shadiakiki1986** [comment]
Where is the code for your spider? I can't find it on the ssoc18.teamshadi.net server

**Comment by ma-hamdan** [comment]
I just added the code. It is similar to the one in the tutorial.

**Comment by shadiakiki1986** [comment]
can you please run this spider on the ssoc18 server and use the `-o quotes.json` option so that I see what your scraped items look like?

**Comment by shadiakiki1986** [comment]
Any updates?

**Comment by ma-hamdan** [comment]
The full scrapy project with the json file is on the server now.

**Comment by shadiakiki1986** [comment]
Can you add a README file with instructions on how to run your spider?

**Comment by shadiakiki1986** [comment]
Also, the server has installed
- [mongodb](https://www.mongodb.com/): nosql database
  - running on default port 27017
- [adminMongo](https://github.com/mrvautin/adminMongo): web UI to view mongodb databases
  - running at ssoc18.teamshadi.net:4321

Please add the [mongo pipeline](https://docs.scrapy.org/en/latest/topics/item-pipeline.html#write-items-to-mongodb) to your spider to store the items in a mongo database, log into adminMongo, and paste a screenshot of your items showing up there.

**Comment by ma-hamdan** [comment]
![image](https://user-images.githubusercontent.com/40775601/44007597-58e1a500-9ea1-11e8-9c69-1c17f772aa59.png)

**Comment by shadiakiki1986** [comment]
LGTM. Let's take it a step further and plot a histogram of the number of books per author. Please create a jupyter notebook that connects to this mongo database using `pymongo` and use `matplotlib` to plot the histogram.
