### ISSUE TITLE
[mickmek] explore quickfix client/server

### ISSUE THREAD

**Issue by shadiakiki1986** [teamshadi/ssoc18#3]
Hi @mickmek

This is just a placeholder for our next project to set up [quickfix](http://www.quickfixengine.org/) client/server.
We will fill in the steps breakdown later.

Steps
- [x] play around with example quickfix python clients (~3h)
    - [x] https://github.com/tianyilai/QuickFix-python-client
        - this contains both a server and a client in python
        - mentions the [Wireshark FIX protocol dissector](https://www.wireshark.org/docs/dfref/f/fix.html)
        - this turned out to be python2 and probably not maintained
    - [x] https://github.com/fvmt/quickfix-python-sample
        - this is only a client
        - this turned out to be python2 and probably not maintained

- [x] ~~~play around with the quickfix python examples in the [original repo](https://github.com/quickfix/quickfix)~~~
    - [x] get the executor running (~1h)
    - ~~~write up a tradeclient in python since not already available (0h)~~~
        - will skip because already available in golang
- [x] run executor and trade client from quickfix/golang examples (~3h)
    - put a few screenshots
    - make sure to use the ID field from the config (either executor or trade client, can't remember)
    - move to using the ssoc18.teamshadi.net server so that we can communicate more efficiently about this
- [ ] try out the [Wireshark FIX protocol dissector](https://www.wireshark.org/docs/dfref/f/fix.html) mentioned above (~3h)
    - [x] install and run on local laptop (via wireshark qt gui)
    - [ ] install and run on ssoc18.teamshadi.net server (via tshark console interface) (~1h)
- [ ] add logic in our own executor
    - [x] send email upon order reception (~3h)
    - [x] if symbol != "BTCUSD", reject order, otherwise accept it (~2h)
    - [x] if abs(qty) > 100, reject order, otherwise accept it (~2h)
    - [x] read best and most recent bid/ask from recorded database into golang (~2h)
    - [ ] if abs(price - best bid/ask from recorded database) / price > 5%, reject order, otherwise accept it (~1h)
- [ ] wrap the tradeclient (golang or python) in a web UI or a local desktop GUI
    - research (~1h)
    - trying out one or two alternatives (~4h)

**Comment by shadiakiki1986** [comment]
@MickMek I added some points above

**Comment by MickMek** [comment]
Ran tradeclient and executor on local computer, screenshots below:

<img width="1280" alt="login" src="https://user-images.githubusercontent.com/40487507/42379521-8c7a2b84-8133-11e8-8c58-3e4041e0a459.png">
<img width="1280" alt="enter_order" src="https://user-images.githubusercontent.com/40487507/42379524-8f174dc2-8133-11e8-9842-da82ec75842d.png">
<img width="1280" alt="quit" src="https://user-images.githubusercontent.com/40487507/42379526-90a8e16e-8133-11e8-9358-e525515a0cb2.png">

Issues:
-Not sure what is `ClOrdID` tag, cannot find it in config
-Unable to run quickfix on server, error: "The program 'go' is currently not installed. To run 'go' please ask your administrator to install the package 'golang-go'"

**Comment by shadiakiki1986** [comment]
@MickMek fixed go issue on server. Try again now please

```
ubuntu@ssoc18:~$ go version
go version go1.6.2 linux/amd64
```

**Comment by shadiakiki1986** [comment]
ClOrdID is not available in the config?

**Comment by MickMek** [comment]
quickfix successful set-up on server, screenshot below:
<img width="1280" alt="screen shot 2018-07-06 at 4 47 24 pm" src="https://user-images.githubusercontent.com/40487507/42382266-739cd644-813c-11e8-91b7-75cbd3c3918e.png">

**Comment by MickMek** [comment]
Update:

Successful set up for wireshark (on local PC), with filter: `fix.MsgType != "0" && fix`
Screenshots below:
<img width="870" alt="screen shot 2018-07-11 at 2 30 09 pm" src="https://user-images.githubusercontent.com/40487507/42722014-55b050ae-874d-11e8-826f-57d7cf6d34f3.png">


Added below logic to our executor:
-	Symbol (only accept BTCUSD)
-	Price (only accept trades lower than 100)
-	Send email when trade is successfully processed

Notes:
Must specify GOPATH as follows: `export GOPATH=$HOME/3-quickfix/go/`
If executor was not exited properly in the last use, must kill running instance in port:
lsof -i 
kill -9 < PID >

Issues:
-	Unable to connect to cryppro_v0 database to retrieve best ask/bid
The package database/sql (used to connect to the database) requires a driver to read `postgre`, which is not available under Go 1.6

**Comment by shadiakiki1986** [comment]
About your issue with golang and postgresql, you need to complement `database/sql` with `github.com/lib/pq`. Check [here](https://astaxie.gitbooks.io/build-web-application-with-golang/en/05.4.html) for an example.

**Comment by shadiakiki1986** [comment]
Btw, just for the sake of doing an example, put me on the email CC list and submit an order from the trade client to the executor. I'd like to see the email arrive in my mailbox

**Comment by MickMek** [comment]
Added you to the mailing list.

For the database, upon trying to complement `database/sql` with `GitHub.com/lib/pq`, got the error:
unrecognized import path "context"

It seems this "context" package was added to Go 1.7 but not 1.6, that is why there are no proper drivers to read the database (same case for mysql and other drivers).
I have tried other packages, such as:
github.com/bmizerany/pq
github.com/lxn/go-pgsql
But no luck..

**Comment by shadiakiki1986** [comment]
Ok I see. We can just update the go on the server to a more recent version

**Comment by shadiakiki1986** [comment]
- go 1.10 installed on server
- go 1.6 was the older version, and it is still available via `/usr/lib/go-1.6/bin/go`

**Comment by MickMek** [comment]
Update:
Added all required logic to our executor
Added messages to our tradeclient, informing on our conditions.

Issues:
Unable to collect packages with tshark from the Loopback interface, screenshot below:
<img width="942" alt="screen shot 2018-07-17 at 2 00 56 pm" src="https://user-images.githubusercontent.com/40487507/42813632-534433e2-89ca-11e8-822d-aaed026068ae.png">

**Comment by shadiakiki1986** [comment]
Looks like you will need sudo access. Let me try it out as admin and let
you know. Meanwhile, please look into whether or not quickfix has a
web-based trade client available. Maybe somebody already built one. If not,
let's look into how to build a web app that wraps the quickfix trade
client. Was there a trade client already implemented in python? (I don't
remember if it was the trade client or the executor). If yes, then flask
would be a good choice for a framework. If not, let's see what web
development framework is available for golang since we already have that
one working. Then let's rewrite the golang trade client to become a web app
instead of a console app.
Shadi

**Comment by shadiakiki1986** [comment]
Migrated to https://github.com/SSOC18/quickfix-executor/issues/2
