### ISSUE TITLE
[registration] Fatima Fawaz

### ISSUE THREAD

**Issue by FatimaFawaz** [teamshadi/ssoc18#4]
## If you are registering for SSOC18 ...

Please fill in the below form:

1. Name: Fatme Fawaz
2. University: AUB
3. Department: ECE 
4. Expected graduation date: July 2018
5. How's your availability during July? at least 4 hours a day
6. How's your availability during August? at least 6 hours a day
7. Which project are you interested in? (please choose on of the options below)
  **a. (financial engineering) Market-making cryptocurrencies**
  b. (chemical engineering) AI on cosmetics
  c. (data science) deep learning on Kaggle's [Grasp and Lift EEG detection](https://www.kaggle.com/c/grasp-and-lift-eeg-detection)
8. Most information on this event as well as code is made public by being posted on github.com. Are you ok with that? **Yes**/No
9. Special notes? ...

## If you are just making a general inquiry ...

Go ahead

**Comment by shadiakiki1986** [comment]
Got it. Thanks :)
