### ISSUE TITLE
[registration] Mohammad Ali Hamdan

### ISSUE THREAD

**Issue by ma-hamdan** [teamshadi/ssoc18#8]
## If you are registering for SSOC18 ...

Please fill in the below form:

1. Name: Mohammad Ali Hamdan
2. University: American University of Beirut
3. Department: ECE
4. Expected graduation date: Spring 2019
5. How's your availability during July? a couple of hours per day
6. How's your availability during August? all day
7. Which project are you interested in? (please choose on of the options below)
  (chemical engineering) AI on cosmetics
8. Most information on this event as well as code is made public by being posted on github.com. Are you ok with that? Yes
9. Special notes? 

## If you are just making a general inquiry ...

Go ahead

**Comment by shadiakiki1986** [comment]
Thanks @MohammadAliHamdan for registering. I'll open a new issue to follow up on what you already started on with deepcognition.ai
