### ISSUE TITLE
[MohammadAliHamdan] deepcognition.ai soda bottle competition

### ISSUE THREAD

**Issue by shadiakiki1986** [teamshadi/ssoc18#9]
Hi @MohammadAliHamdan
Let's use this issue to track your progress on deepcognition.ai

- ~~~warm up~~~ (~0h)
    - get familiar with deepcognition.ai
    - train a model for MNIST
        - already done and got ~78% on validation subset
- ~~~soda model v1~~~ (~0h)
    - build a first model, train it, check its score
    - make a submission

**Comment by ma-hamdan** [comment]
![sodaresults](https://user-images.githubusercontent.com/40775601/42739556-fc9886de-88a1-11e8-819e-406ec8559989.PNG)
![sodaresults2](https://user-images.githubusercontent.com/40775601/42739560-1240cfdc-88a2-11e8-85a4-7e2b7fe9b981.PNG)
